### ISSUE TITLE
学期总结

### ISSUE THREAD

**Issue by hlxing** [WestRabbit/semi-monthly-report#6]

**Comment by ldc-37** [comment]
_完了 竟然不知道写什么 看来这一学期全在划水……_ 

- 已完成的任务
1.  通过一学期的纳新考核出题、答疑、分享及审核，提高了代码阅读能力，进一步扎实了基础。
2.  通过fwwb的比赛，深刻体会到了原生js的不方便和现代前端开发方式能带来的好处，也学习使用了sweetalert,dropzone,snarl等jQuery库，初步使用并打算继续学习使用layer来构建页面。外加Photoshop……
3.  看了工作室的几本前端开发的书（不得不说有些内容过时的很快）和各类网上教程，学习了浏览器新API（Ws/IndexedDB/IntersectionObserver等），认识es6，并初步理解了MVC、MVVM框架的概念及它们试图解决的问题，为（已经开始的）现代前端开发的学习做好准备。
4.  参加/举行了几次班级和西二在线的分享会/宣讲/答辩等，感觉心理素质有所提高

- 未完成的任务 
  - 由于自身原因，vue.js的学习推进缓慢。暂时打算先学习微信小程序，之后再继续研究vue.js。
  - 慕课网的一堆课程（node.js）也没有开刷。
 
- 遇到的问题
  - 除了fwwb以外的实践实在有限，寒假希望能多动手。
  - 仍然不适应现代前端开发方式（大概还是写的不够）。
  - 效率低下，另外睡得晚起得晚。。。
  - 审美GG

- 意见和建议
   寒假控制娱乐时间（除了和npy去玩
   **每天都记录一下这一天都摸了哪些鱼= =**

- 寒假计划
  - [x] 学习并制作微信小程序
  - [ ] 通过多多围观设计类公众号，以求提高审美。
  - [x] 预习一下下学期的数据库和Java。
  - [ ] 或许要尝试重写fwwb项目

- 署名：李定成

**Comment by IceQuarze** [comment]
- #### 已完成的任务
	- 深度学习简单涉猎一遍
	- `React`,`React Native`,`Flask`三个框架的学习与应用
- #### 未完成的任务
	- 暂无（稳步地完成自己的计划）
- #### 遇到的问题
	- 自己做的网站系统有时候崩了但是过了许久会想不起之前规划的网站架构
	- 做一个系统功能实现完成但是可能美观上还有待改进，也有可能存在一些`bug`需要时间检验
- #### 寒假计划
	- 优化一下网站，给未来的自己写下文档
- 署名：游先耀

**Comment by Q1176011838** [comment]
- 已完成的任务
  - 完成了服务外包的项目
  - 学习了linux下websocket的开发
  - 通过对18级新生的考核，回顾了自己以前的代码，扫除了一些知识盲点
- 未完成的任务
  - linux学习搁浅
- 遇到的问题
  - 自己做的项目很多都没有考虑高并发问题
  - 几乎没用到啥框架，功能多了以后调试起来很麻烦
- 寒假计划
  - linux学习
  - 做一个公司宣传网站

**Comment by cmdrgh** [comment]
- 已完成任务
   -  通过一学期的前端考核方向的出题、答疑、审核作业，提高了代码审计能力，也复习了部分知识，同时学到了新知识
   -  通过参加了一些ctf比赛，不断学习进步，积累了实战经验
   -  优化了之前的部分网页作品
- 未完成的任务
   -  总结之前赛题的wp，搬到博客
   - 之前马过的很多博客教程还没看
- 遇到的问题
   - 通过和大佬们的学习交流，认识到自己见识和经验还是太少
   - 这学期参加的活动比较多，而且对课内学习不够重视，导致绩点排名下降
- 意见和建议
   -  寒假要合理利用，时间和效率兼顾
   -  下学期课内学习需要重视，保证听课效率，周末合理分配时间
- 寒假计划
   -  搭建个人博客，尝试多种cms
   -  完成商会项目
   -  继续钻研之前打不动的赛题
   -  再有空的话就打一打靶场吧

**Comment by lacxxy** [comment]
- 已完成的任务
  - 在fwwb的比赛中收获了许多，在实践中进一步学习了vue
  - 在fwwb的比赛中了解了许多的html5新特性indexdb,localstorage,notifications,websocket等等
  - 初步的学习es6
  - 初步的学习node和数据库及linux的使用

- 未完成的任务
   - 想试试ctf...还在做题

- 遇到的问题
  - ...大雾挂了（woc）好烦
 
- 意见和建议
  - ...steam卸载

- 寒假计划
  - 用node+vue写个大富翁游戏
  - 博客里多写点东西
  - 完成一个公司宣传网站

**Comment by chenyuyuya** [comment]
* 已完成任务

   * 学习了机器学习的有关算法
   * 熟悉了Python机器学习库

* 未完成任务

   * 深度学习Tensorflow

* 意见和建议

   * 多参加比赛增长见识

* 寒假计划

   * 学习Tensorflow

* 署名:  陈宇
